name: CI/CD - TP - Partie 3
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Lint code
        run: npm run lint

      - name: Install Playwright
        run: npx playwright install --with-deps
        
      - name: Run Playwright tests
        run: npx playwright test
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

      - name: Set variables d'environnement
        run: |
          echo "GITHUB_ACCOUNT=$GITHUB_ACTOR" >> $GITHUB_ENV
          echo "BUILD_DATE=$(date)" >> $GITHUB_ENV

      - name: Build project
        run: npm run build

      - name: Déployer serveur SSH
        run: echo "${{secrets.SSH_KEY}}" > ~/deployement_key && chmod 400 ~/deployement_key

      - name: Déplacer contenu fichier
        run: rsync -Pavz -e "ssh -i ~/deployement_key -o StrictHostKeyChecking=no" dist/ ${{secrets.SSH_USER}}@${{secrets.SSH_SERVER}}:~/www